### PR TITLE
Fix paths to download schema versions regarding code moving to src folder

### PR DESCRIPTION
**Pull request by benoitblanc**
Hi,

As code moved to `src` folder recently, we need to adapt paths to get schema versions file, if I understand it right :sweat_smile: 

Thanks

### CODE REVIEW

**Comment by manisandro** [comment]
The paths should be correct as it stands as the schemas are copied separately in the Dockerfile [1]. Do you get any error?

[1] https://github.com/qwc-services/qwc-config-generator/blob/d04a41670af9c4f757f8da9cd2d34c34820b6851/Dockerfile#L21

**Comment by benoitblanc** [comment]
Hm yes, I don't use Docker in this case, I am running qwc-services with uwsgi... I'm going to look into it if there is solution for both cases...

```
ERROR: Could not load JSON schema versions from /opt/qwc-services/qwc-config-generator/src/config_generator/../schemas/schema-versions.json:
[Errno 2] No such file or directory: '/opt/qwc-services/qwc-config-generator/src/config_generator/../schemas/schema-versions.json'
```

**Comment by manisandro** [comment]
One solution would be to move `schema-versions.json` inside the `src` folder as it is technically not a schema anyway.

**Comment by benoitblanc** [comment]
@manisandro thanks for the advice. I have moved `schema-versions.json` to the `src` folder.

I am not sure, but is it still needed to add schemas folder to `/srv/qwc-services/schemas`  in Dockerfiles ?

**Comment by manisandro** [comment]
LGTM, thanks!

**Pull request merged**
